package com.murik.lite.presentation.presenter.substances;

import com.murik.lite.model.substances.Substance;
import com.murik.lite.model.substances.ValueInRange;

import java.util.Arrays;
import java.util.List;

public class SubstancesUtils {

    public static List<Substance> getSubstances(SubstancesParametersData parametersData) {
        return Arrays.asList(
                new Substance("Вода",
                        new ValueInRange(parametersData.getII(), 0.64, 0.68),
                        new ValueInRange(parametersData.getIII(), 0.40, 0.48),
                        new ValueInRange(parametersData.getV(), 0.22, 0.27),
                        new ValueInRange(parametersData.getIV(), 0.48, 0.53),
                        new ValueInRange(parametersData.getT_60(), 52, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.16, 0.21),
                        new ValueInRange(parametersData.getS_15_30(), 0.14, 0.16),
                        new ValueInRange(parametersData.getVI_L(), 0.41, 0.51),
                        new ValueInRange(parametersData.getVII_L(), 0.62, 0.65),
                        new ValueInRange(parametersData.getII_30(), 0.21, 0.33),
                        new ValueInRange(parametersData.getI_30(), 0.14, 0.28)
                ),
                new Substance("Бутанол-1",
                        new ValueInRange(parametersData.getII(), 0.64, 0.65),
                        new ValueInRange(parametersData.getIII(), 0.44, 0.49),
                        new ValueInRange(parametersData.getV(), 0.23, 0.33),
                        new ValueInRange(parametersData.getIV(), 0.53, 0.67),
                        new ValueInRange(parametersData.getT_60(), 54, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.26),
                        new ValueInRange(parametersData.getS_15_30(), 0.11, 0.15),
                        new ValueInRange(parametersData.getVI_L(), 0.45, 0.54),
                        new ValueInRange(parametersData.getVII_L(), 0.59, 0.62),
                        new ValueInRange(parametersData.getII_30(), 0.26, 0.35),
                        new ValueInRange(parametersData.getI_30(), 0.18, 0.25)
                ),
                new Substance("Бутанол-2",
                        new ValueInRange(parametersData.getII(), 0.55, 0.66),
                        new ValueInRange(parametersData.getIII(), 0.27, 0.50),
                        new ValueInRange(parametersData.getV(), 0.10, 0.30),
                        new ValueInRange(parametersData.getIV(), 0.33, 0.50),
                        new ValueInRange(parametersData.getT_60(), 42, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.13, 0.23),
                        new ValueInRange(parametersData.getS_15_30(), 0.16, 0.23),
                        new ValueInRange(parametersData.getVI_L(), 0.29, 0.51),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.68),
                        new ValueInRange(parametersData.getII_30(), 0.33, 0.36),
                        new ValueInRange(parametersData.getI_30(), 0.29, 0.33)
                ),
                new Substance("Этанол",
                        new ValueInRange(parametersData.getII(), 0.64, 0.66),
                        new ValueInRange(parametersData.getIII(), 0.43, 0.48),
                        new ValueInRange(parametersData.getV(), 0.23, 0.27),
                        new ValueInRange(parametersData.getIV(), 0.54, 0.66),
                        new ValueInRange(parametersData.getT_60(), 54, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.25),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.22),
                        new ValueInRange(parametersData.getVI_L(), 0.48, 0.49),
                        new ValueInRange(parametersData.getVII_L(), 0.60, 0.63),
                        new ValueInRange(parametersData.getII_30(), 0.33, 0.46),
                        new ValueInRange(parametersData.getI_30(), 0.26, 0.28)
                ),
                new Substance("Пентанол-2",
                        new ValueInRange(parametersData.getII(), 0.50, 0.63),
                        new ValueInRange(parametersData.getIII(), 0.31, 0.48),
                        new ValueInRange(parametersData.getV(), 0.31, 0.40),
                        new ValueInRange(parametersData.getIV(), 0.75, 0.83),
                        new ValueInRange(parametersData.getT_60(), 48, 54),
                        new ValueInRange(parametersData.getS_30_60(), 0.27, 0.30),
                        new ValueInRange(parametersData.getS_15_30(), 0.30, 0.36),
                        new ValueInRange(parametersData.getVI_L(), 0.50, 0.56),
                        new ValueInRange(parametersData.getVII_L(), 0.80, 1.20),
                        new ValueInRange(parametersData.getII_30(), 0.5, 0.67),
                        new ValueInRange(parametersData.getI_30(), 0.5, 0.9)
                ),
                new Substance("Циклогексанон",
                        new ValueInRange(parametersData.getII(), 0.69, 0.72),
                        new ValueInRange(parametersData.getIII(), 0.5, 0.52),
                        new ValueInRange(parametersData.getV(), 0.28, 0.32),
                        new ValueInRange(parametersData.getIV(), 0.58, 0.6),
                        new ValueInRange(parametersData.getT_60(), 60, 62),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.17, 0.18),
                        new ValueInRange(parametersData.getVI_L(), 0.5, 0.53),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.66),
                        new ValueInRange(parametersData.getII_30(), 0.34, 0.37),
                        new ValueInRange(parametersData.getI_30(), 0.26, 0.31)
                ),
                new Substance("Ацетон",
                        new ValueInRange(parametersData.getII(), 0.66, 0.84),
                        new ValueInRange(parametersData.getIII(), 0.5, 0.63),
                        new ValueInRange(parametersData.getV(), 0.29, 0.36),
                        new ValueInRange(parametersData.getIV(), 0.55, 0.64),
                        new ValueInRange(parametersData.getT_60(), 60, 68),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.23),
                        new ValueInRange(parametersData.getS_15_30(), 0.13, 0.20),
                        new ValueInRange(parametersData.getVI_L(), 0.51, 0.57),
                        new ValueInRange(parametersData.getVII_L(), 0.55, 0.70),
                        new ValueInRange(parametersData.getII_30(), 0.25, 0.37),
                        new ValueInRange(parametersData.getI_30(), 0.2, 0.39)
                ),
                new Substance("Ацетальдегид",
                        new ValueInRange(parametersData.getII(), 0.58, 0.7),
                        new ValueInRange(parametersData.getIII(), 0.42, 0.51),
                        new ValueInRange(parametersData.getV(), 0.21, 0.3),
                        new ValueInRange(parametersData.getIV(), 0.51, 0.59),
                        new ValueInRange(parametersData.getT_60(), 52, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.17, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.12, 0.18),
                        new ValueInRange(parametersData.getVI_L(), 0.43, 0.51),
                        new ValueInRange(parametersData.getVII_L(), 0.58, 0.66),
                        new ValueInRange(parametersData.getII_30(), 0.27, 0.35),
                        new ValueInRange(parametersData.getI_30(), 0.18, 0.33)
                ),
                new Substance("Метиламин",
                        new ValueInRange(parametersData.getII(), 0.51, 0.58),
                        new ValueInRange(parametersData.getIII(), 0.31, 0.38),
                        new ValueInRange(parametersData.getV(), 0.16, 0.2),
                        new ValueInRange(parametersData.getIV(), 0.51, 0.55),
                        new ValueInRange(parametersData.getT_60(), 40, 48),
                        new ValueInRange(parametersData.getS_30_60(), 0.15, 0.17),
                        new ValueInRange(parametersData.getS_15_30(), 0.14, 0.19),
                        new ValueInRange(parametersData.getVI_L(), 0.36, 0.4),
                        new ValueInRange(parametersData.getVII_L(), 0.62, 0.69),
                        new ValueInRange(parametersData.getII_30(), 0.3, 0.35),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.37)
                ),
                new Substance("Диэтиламин",
                        new ValueInRange(parametersData.getII(), 0.53, 0.7),
                        new ValueInRange(parametersData.getIII(), 0.32, 0.5),
                        new ValueInRange(parametersData.getV(), 0.13, 0.3),
                        new ValueInRange(parametersData.getIV(), 0.55, 0.69),
                        new ValueInRange(parametersData.getT_60(), 42, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.14, 0.27),
                        new ValueInRange(parametersData.getS_15_30(), 0.1, 0.15),
                        new ValueInRange(parametersData.getVI_L(), 0.49, 0.64),
                        new ValueInRange(parametersData.getVII_L(), 0.62, 0.73),
                        new ValueInRange(parametersData.getII_30(), 0.32, 0.48),
                        new ValueInRange(parametersData.getI_30(), 0.26, 0.41)
                ),
                new Substance("Муравьиная кислота",
                        new ValueInRange(parametersData.getII(), 0.6, 0.65),
                        new ValueInRange(parametersData.getIII(), 0.4, 0.45),
                        new ValueInRange(parametersData.getV(), 0.2, 0.24),
                        new ValueInRange(parametersData.getIV(), 0.51, 0.54),
                        new ValueInRange(parametersData.getT_60(), 48, 54),
                        new ValueInRange(parametersData.getS_30_60(), 0.17, 0.19),
                        new ValueInRange(parametersData.getS_15_30(), 0.13, 0.15),
                        new ValueInRange(parametersData.getVI_L(), 0.41, 0.47),
                        new ValueInRange(parametersData.getVII_L(), 0.57, 0.6),
                        new ValueInRange(parametersData.getII_30(), 0.26, 0.29),
                        new ValueInRange(parametersData.getI_30(), 0.21, 0.26)
                ),
                new Substance("Уксусная кислота",
                        new ValueInRange(parametersData.getII(), 0.6, 0.62),
                        new ValueInRange(parametersData.getIII(), 0.4, 0.42),
                        new ValueInRange(parametersData.getV(), 0.22, 0.23),
                        new ValueInRange(parametersData.getIV(), 0.53, 0.55),
                        new ValueInRange(parametersData.getT_60(), 50, 52),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.19),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.16),
                        new ValueInRange(parametersData.getVI_L(), 0.45, 0.47),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.63),
                        new ValueInRange(parametersData.getII_30(), 0.29, 0.32),
                        new ValueInRange(parametersData.getI_30(), 0.25, 0.28)
                ),
                new Substance("Молочная кислота",
                        new ValueInRange(parametersData.getII(), 0.65, 0.73),
                        new ValueInRange(parametersData.getIII(), 0.46, 0.56),
                        new ValueInRange(parametersData.getV(), 0.26, 0.36),
                        new ValueInRange(parametersData.getIV(), 0.56, 0.67),
                        new ValueInRange(parametersData.getT_60(), 60, 66),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.25),
                        new ValueInRange(parametersData.getS_15_30(), 0.14, 0.21),
                        new ValueInRange(parametersData.getVI_L(), 0.47, 0.57),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.67),
                        new ValueInRange(parametersData.getII_30(), 0.3, 0.44),
                        new ValueInRange(parametersData.getI_30(), 0.29, 0.38)
                ),
                new Substance("Масляная кислота",
                        new ValueInRange(parametersData.getII(), 0.66, 0.7),
                        new ValueInRange(parametersData.getIII(), 0.37, 0.5),
                        new ValueInRange(parametersData.getV(), 0.2, 0.27),
                        new ValueInRange(parametersData.getIV(), 0.42, 0.54),
                        new ValueInRange(parametersData.getT_60(), 36, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.11, 0.13),
                        new ValueInRange(parametersData.getVI_L(), 0.31, 0.43),
                        new ValueInRange(parametersData.getVII_L(), 0.57, 0.6),
                        new ValueInRange(parametersData.getII_30(), 0.25, 0.36),
                        new ValueInRange(parametersData.getI_30(), 0, 0.2)
                ),
                new Substance("Пентанол-1",
                        new ValueInRange(parametersData.getII(), 0.58, 0.63),
                        new ValueInRange(parametersData.getIII(), 0.35, 0.39),
                        new ValueInRange(parametersData.getV(), 0.15, 0.18),
                        new ValueInRange(parametersData.getIV(), 0.4, 0.44),
                        new ValueInRange(parametersData.getT_60(), 46, 48),
                        new ValueInRange(parametersData.getS_30_60(), 0.14, 0.16),
                        new ValueInRange(parametersData.getS_15_30(), 0.08, 0.12),
                        new ValueInRange(parametersData.getVI_L(), 0.39, 0.42),
                        new ValueInRange(parametersData.getVII_L(), 0.50, 0.80),
                        new ValueInRange(parametersData.getII_30(), 0.16, 0.22),
                        new ValueInRange(parametersData.getI_30(), -0.11, 0.12)
                ),
                new Substance("Метилэтилкетон",
                        new ValueInRange(parametersData.getII(), 0.63, 0.76),
                        new ValueInRange(parametersData.getIII(), 0.46, 0.56),
                        new ValueInRange(parametersData.getV(), 0.26, 0.33),
                        new ValueInRange(parametersData.getIV(), 0.56, 0.6),
                        new ValueInRange(parametersData.getT_60(), 56, 66),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.24),
                        new ValueInRange(parametersData.getS_15_30(), 0.17, 0.18),
                        new ValueInRange(parametersData.getVI_L(), 0.49, 0.54),
                        new ValueInRange(parametersData.getVII_L(), 0.65, 0.68),
                        new ValueInRange(parametersData.getII_30(), 0.33, 0.36),
                        new ValueInRange(parametersData.getI_30(), 0.30, 0.33)
                ),
                new Substance("Хлороформ",
                        new ValueInRange(parametersData.getII(), 0.64, 0.66),
                        new ValueInRange(parametersData.getIII(), 0.45, 0.47),
                        new ValueInRange(parametersData.getV(), 0.25, 0.27),
                        new ValueInRange(parametersData.getIV(), 0.5, 0.58),
                        new ValueInRange(parametersData.getT_60(), 55, 57),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.21),
                        new ValueInRange(parametersData.getS_15_30(), 0.16, 0.17),
                        new ValueInRange(parametersData.getVI_L(), 0.40, 0.48),
                        new ValueInRange(parametersData.getVII_L(), 0.62, 0.63),
                        new ValueInRange(parametersData.getII_30(), 0.32, 0.34),
                        new ValueInRange(parametersData.getI_30(), 0.30, 0.40)
                ),
                new Substance("Пропионовая кислота",
                        new ValueInRange(parametersData.getII(), 0.58, 0.62),
                        new ValueInRange(parametersData.getIII(), 0.41, 0.51),
                        new ValueInRange(parametersData.getV(), 0.22, 0.28),
                        new ValueInRange(parametersData.getIV(), 0.53, 0.55),
                        new ValueInRange(parametersData.getT_60(), 52, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.20),
                        new ValueInRange(parametersData.getS_15_30(), 0.14, 0.16),
                        new ValueInRange(parametersData.getVI_L(), 0.38, 0.44),
                        new ValueInRange(parametersData.getVII_L(), 0.62, 0.63),
                        new ValueInRange(parametersData.getII_30(), 0.31, 0.32),
                        new ValueInRange(parametersData.getI_30(), 0.25, 0.28)
                ),
                new Substance("Уксус 1М",
                        new ValueInRange(parametersData.getII(), 0.65, 0.71),
                        new ValueInRange(parametersData.getIII(), 0.45, 0.52),
                        new ValueInRange(parametersData.getV(), 0.23, 0.3),
                        new ValueInRange(parametersData.getIV(), 0.52, 0.58),
                        new ValueInRange(parametersData.getT_60(), 56, 62),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.20),
                        new ValueInRange(parametersData.getS_15_30(), 0.11, 0.19),
                        new ValueInRange(parametersData.getVI_L(), 0.45, 0.47),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.67),
                        new ValueInRange(parametersData.getII_30(), 0.30, 0.34),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.29)
                ),
                new Substance("Аммиак, 10 %",
                        new ValueInRange(parametersData.getII(), 0.68, 0.70),
                        new ValueInRange(parametersData.getIII(), 0.47, 0.51),
                        new ValueInRange(parametersData.getV(), 0.26, 0.30),
                        new ValueInRange(parametersData.getIV(), 0.56, 0.59),
                        new ValueInRange(parametersData.getT_60(), 56, 62),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.19),
                        new ValueInRange(parametersData.getVI_L(), 0.47, 0.52),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.66),
                        new ValueInRange(parametersData.getII_30(), 0.33, 0.37),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.34)
                ),
                new Substance("Хлороформ толуол (3:1)",
                        new ValueInRange(parametersData.getII(), 0.58, 0.64),
                        new ValueInRange(parametersData.getIII(), 0.36, 0.44),
                        new ValueInRange(parametersData.getV(), 0.15, 0.24),
                        new ValueInRange(parametersData.getIV(), 0.42, 0.53),
                        new ValueInRange(parametersData.getT_60(), 46, 54),
                        new ValueInRange(parametersData.getS_30_60(), 0.14, 0.19),
                        new ValueInRange(parametersData.getS_15_30(), 0.08, 0.16),
                        new ValueInRange(parametersData.getVI_L(), 0.35, 0.45),
                        new ValueInRange(parametersData.getVII_L(), 0.4, 0.62),
                        new ValueInRange(parametersData.getII_30(), 0.14, 0.31),
                        new ValueInRange(parametersData.getI_30(), 0.06, 0.27)
                ),
                new Substance("1,4-Диоксан",
                        new ValueInRange(parametersData.getII(), 0.62, 0.63),
                        new ValueInRange(parametersData.getIII(), 0.42, 0.43),
                        new ValueInRange(parametersData.getV(), 0.23, 0.24),
                        new ValueInRange(parametersData.getIV(), 0.53, 0.57),
                        new ValueInRange(parametersData.getT_60(), 51, 52),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.19),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.17),
                        new ValueInRange(parametersData.getVI_L(), 0.45, 0.46),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.64),
                        new ValueInRange(parametersData.getII_30(), 0.32, 0.33),
                        new ValueInRange(parametersData.getI_30(), 0.25, 0.3)
                ),
                new Substance("Метоксиуксусная кислота",
                        new ValueInRange(parametersData.getII(), 0.66, 0.68),
                        new ValueInRange(parametersData.getIII(), 0.45, 0.47),
                        new ValueInRange(parametersData.getV(), 0.23, 0.25),
                        new ValueInRange(parametersData.getIV(), 0.54, 0.56),
                        new ValueInRange(parametersData.getT_60(), 57, 59),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.20),
                        new ValueInRange(parametersData.getS_15_30(), 0.17, 0.18),
                        new ValueInRange(parametersData.getVI_L(), 0.47, 0.48),
                        new ValueInRange(parametersData.getVII_L(), 0.66, 0.67),
                        new ValueInRange(parametersData.getII_30(), 0.30, 0.33),
                        new ValueInRange(parametersData.getI_30(), 0.29, 0.3)
                ),
                new Substance("Циклопентиламин",
                        new ValueInRange(parametersData.getII(), 0.51, 0.52),
                        new ValueInRange(parametersData.getIII(), 0.31, 0.33),
                        new ValueInRange(parametersData.getV(), 0.12, 0.15),
                        new ValueInRange(parametersData.getIV(), 0.38, 0.47),
                        new ValueInRange(parametersData.getT_60(), 41, 43),
                        new ValueInRange(parametersData.getS_30_60(), 0.12, 0.15),
                        new ValueInRange(parametersData.getS_15_30(), 0.04, 0.12),
                        new ValueInRange(parametersData.getVI_L(), 0.33, 0.37),
                        new ValueInRange(parametersData.getVII_L(), 0.34, 0.54),
                        new ValueInRange(parametersData.getII_30(), 0.10, 0.23),
                        new ValueInRange(parametersData.getI_30(), 0.03, 0.24)
                ),
                new Substance("Моноэтаноламин",
                        new ValueInRange(parametersData.getII(), 0.63, 0.68),
                        new ValueInRange(parametersData.getIII(), 0.46, 0.49),
                        new ValueInRange(parametersData.getV(), 0.27, 0.3),
                        new ValueInRange(parametersData.getIV(), 0.59, 0.61),
                        new ValueInRange(parametersData.getT_60(), 56, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.2),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.17),
                        new ValueInRange(parametersData.getVI_L(), 0.44, 0.49),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.61),
                        new ValueInRange(parametersData.getII_30(), 0.31, 0.32),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.31)
                ),
                new Substance("Диэтаноламин",
                        new ValueInRange(parametersData.getII(), 0.63, 0.66),
                        new ValueInRange(parametersData.getIII(), 0.43, 0.45),
                        new ValueInRange(parametersData.getV(), 0.24, 0.25),
                        new ValueInRange(parametersData.getIV(), 0.54, 0.56),
                        new ValueInRange(parametersData.getT_60(), 54, 56),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.19),
                        new ValueInRange(parametersData.getS_15_30(), 0.13, 0.14),
                        new ValueInRange(parametersData.getVI_L(), 0.46, 0.47),
                        new ValueInRange(parametersData.getVII_L(), 0.58, 0.62),
                        new ValueInRange(parametersData.getII_30(), 0.29, 0.31),
                        new ValueInRange(parametersData.getI_30(), 0.22, 0.23)
                ),
                new Substance("Метоксиэтанамин (4-метилморфолин)",
                        new ValueInRange(parametersData.getII(), 0.50, 0.51),
                        new ValueInRange(parametersData.getIII(), 0.26, 0.3),
                        new ValueInRange(parametersData.getV(), 0.06, 0.14),
                        new ValueInRange(parametersData.getIV(), 0.22, 0.45),
                        new ValueInRange(parametersData.getT_60(), 38, 40),
                        new ValueInRange(parametersData.getS_30_60(), 0.11, 0.13),
                        new ValueInRange(parametersData.getS_15_30(), 0.09, 0.12),
                        new ValueInRange(parametersData.getVI_L(), 0.29, 0.34),
                        new ValueInRange(parametersData.getVII_L(), 0.5, 0.51),
                        new ValueInRange(parametersData.getII_30(), 0.12, 0.2),
                        new ValueInRange(parametersData.getI_30(), -0.33, 0.11)
                ),
                new Substance("Морфолин",
                        new ValueInRange(parametersData.getII(), -0.10, 0.29),
                        new ValueInRange(parametersData.getIII(), -0.4, 0.03),
                        new ValueInRange(parametersData.getV(), -0.4, -0.1),
                        new ValueInRange(parametersData.getIV(), -2.20, 1),
                        new ValueInRange(parametersData.getT_60(), 16, 28),
                        new ValueInRange(parametersData.getS_30_60(), 0.12, 0.42),
                        new ValueInRange(parametersData.getS_15_30(), 0.27, 0.47),
                        new ValueInRange(parametersData.getVI_L(), -2.9, -0.1),
                        new ValueInRange(parametersData.getVII_L(), 0.85, 1.2),
                        new ValueInRange(parametersData.getII_30(), -7.3, 0.79),
                        new ValueInRange(parametersData.getI_30(), -0.47, 0.76)
                ),
                new Substance("Аминопропиламидозол",
                        new ValueInRange(parametersData.getII(), 0.64, 0.65),
                        new ValueInRange(parametersData.getIII(), 0.43, 0.46),
                        new ValueInRange(parametersData.getV(), 0.24, 0.25),
                        new ValueInRange(parametersData.getIV(), 0.56, 0.58),
                        new ValueInRange(parametersData.getT_60(), 52, 56),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.2),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.17),
                        new ValueInRange(parametersData.getVI_L(), 0.44, 0.49),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.61),
                        new ValueInRange(parametersData.getII_30(), 0.32, 0.33),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.31)
                ),
                new Substance("МетилОэтиламин",
                        new ValueInRange(parametersData.getII(), 0.47, 0.5),
                        new ValueInRange(parametersData.getIII(), 0.24, 0.27),
                        new ValueInRange(parametersData.getV(), 0.05, 0.08),
                        new ValueInRange(parametersData.getIV(), 0.2, 0.34),
                        new ValueInRange(parametersData.getT_60(), 38, 40),
                        new ValueInRange(parametersData.getS_30_60(), 0.1, 0.11),
                        new ValueInRange(parametersData.getS_15_30(), 0.08, 0.2),
                        new ValueInRange(parametersData.getVI_L(), 0.24, 0.4),
                        new ValueInRange(parametersData.getVII_L(), 0.47, 0.66),
                        new ValueInRange(parametersData.getII_30(), 0.15, 0.36),
                        new ValueInRange(parametersData.getI_30(), 0.2, 0.48)
                ),
                new Substance("Гексанон",
                        new ValueInRange(parametersData.getII(), 0.57, 0.62),
                        new ValueInRange(parametersData.getIII(), 0.29, 0.38),
                        new ValueInRange(parametersData.getV(), 0.14, 0.25),
                        new ValueInRange(parametersData.getIV(), 0.5, 0.67),
                        new ValueInRange(parametersData.getT_60(), 36, 42),
                        new ValueInRange(parametersData.getS_30_60(), 0.19, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.08, 0.12),
                        new ValueInRange(parametersData.getVI_L(), 0.2, 0.33),
                        new ValueInRange(parametersData.getVII_L(), 0.5, 0.8),
                        new ValueInRange(parametersData.getII_30(), 0, 0.22),
                        new ValueInRange(parametersData.getI_30(), 0, Integer.MAX_VALUE)
                ),
                new Substance("Дексаметазон",
                        new ValueInRange(parametersData.getII(), 0.69, 0.73),
                        new ValueInRange(parametersData.getIII(), 0.62, 0.66),
                        new ValueInRange(parametersData.getV(), 0.46, 0.5),
                        new ValueInRange(parametersData.getIV(), 0.7, 0.77),
                        new ValueInRange(parametersData.getT_60(), 76, 80),
                        new ValueInRange(parametersData.getS_30_60(), 0.28, 0.31),
                        new ValueInRange(parametersData.getS_15_30(), 0.21, 0.24),
                        new ValueInRange(parametersData.getVI_L(), 0.7, 0.74),
                        new ValueInRange(parametersData.getVII_L(), 0.46, 0.5),
                        new ValueInRange(parametersData.getII_30(), 0.48, 0.51),
                        new ValueInRange(parametersData.getI_30(), 0.4, 0.45)
                ),
                new Substance("Пульмикорт",
                        new ValueInRange(parametersData.getII(), 0.73, 0.77),
                        new ValueInRange(parametersData.getIII(), 0.6, 0.63),
                        new ValueInRange(parametersData.getV(), 0.4, 0.44),
                        new ValueInRange(parametersData.getIV(), 0.7, 0.73),
                        new ValueInRange(parametersData.getT_60(), 70, 73),
                        new ValueInRange(parametersData.getS_30_60(), 0.26, 0.28),
                        new ValueInRange(parametersData.getS_15_30(), 0.22, 0.24),
                        new ValueInRange(parametersData.getVI_L(), 0.7, 0.7),
                        new ValueInRange(parametersData.getVII_L(), 0.46, 0.5),
                        new ValueInRange(parametersData.getII_30(), 0.46, 0.49),
                        new ValueInRange(parametersData.getI_30(), 0.43, 0.46)
                ),
                new Substance("Серотонин",
                        new ValueInRange(parametersData.getII(), 0.71, 0.74),
                        new ValueInRange(parametersData.getIII(), 0.6, 0.63),
                        new ValueInRange(parametersData.getV(), 0.36, 0.4),
                        new ValueInRange(parametersData.getIV(), 0.6, 0.63),
                        new ValueInRange(parametersData.getT_60(), 68, 72),
                        new ValueInRange(parametersData.getS_30_60(), 0.24, 0.27),
                        new ValueInRange(parametersData.getS_15_30(), 0.19, 0.22),
                        new ValueInRange(parametersData.getVI_L(), 0.6, 0.64),
                        new ValueInRange(parametersData.getVII_L(), 0.44, 0.47),
                        new ValueInRange(parametersData.getII_30(), 0.46, 0.48),
                        new ValueInRange(parametersData.getI_30(), 0.28, 0.3)
                )
        );
    }

    public static List<Substance> getObjects(SubstancesParametersData parametersData) {
        return Arrays.asList(
                new Substance("Тюльпаны розовые",
                        new ValueInRange(parametersData.getII(), 0.6, 0.66),
                        new ValueInRange(parametersData.getIII(), 0.35, 0.43),
                        new ValueInRange(parametersData.getV(), 0.14, 0.2),
                        new ValueInRange(parametersData.getIV(), 0.4, 0.47),
                        new ValueInRange(parametersData.getT_60(), 45, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.13, 0.17),
                        new ValueInRange(parametersData.getS_15_30(), 0.01, 0.04),
                        new ValueInRange(parametersData.getVI_L(), 0.35, 0.45),
                        new ValueInRange(parametersData.getVII_L(), 0.4, 0.47),
                        new ValueInRange(parametersData.getII_30(), 0.14, 0.2),
                        new ValueInRange(parametersData.getI_30(), 0.0, 1.0)
                ),
                new Substance("Орхидеи фиолетовые",
                        new ValueInRange(parametersData.getII(), 0.8, 0.84),
                        new ValueInRange(parametersData.getIII(), 0.58, 0.76),
                        new ValueInRange(parametersData.getV(), 0.34, 0.52),
                        new ValueInRange(parametersData.getIV(), 0.57, 0.67),
                        new ValueInRange(parametersData.getT_60(), 65, 82),
                        new ValueInRange(parametersData.getS_30_60(), 0.22, 0.3),
                        new ValueInRange(parametersData.getS_15_30(), 0.14, 0.19),
                        new ValueInRange(parametersData.getVI_L(), 0.5, 0.75),
                        new ValueInRange(parametersData.getVII_L(), 0.65, 0.71),
                        new ValueInRange(parametersData.getII_30(), 0.34, 0.44),
                        new ValueInRange(parametersData.getI_30(), 0.28, 0.35)
                ),
                new Substance("Орхидеи белые",
                        new ValueInRange(parametersData.getII(), 0.43, 0.65),
                        new ValueInRange(parametersData.getIII(), 0.36, 0.48),
                        new ValueInRange(parametersData.getV(), 0.15, 0.27),
                        new ValueInRange(parametersData.getIV(), 0.46, 0.58),
                        new ValueInRange(parametersData.getT_60(), 24, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.18, 0.22),
                        new ValueInRange(parametersData.getS_15_30(), 0.15, 0.24),
                        new ValueInRange(parametersData.getVI_L(), 0.46, 0.60),
                        new ValueInRange(parametersData.getVII_L(), 0.65, 0.75),
                        new ValueInRange(parametersData.getII_30(), 0.3, 0.41),
                        new ValueInRange(parametersData.getI_30(), 0.3, 0.52)
                ),
                new Substance("Розы розовые",
                        new ValueInRange(parametersData.getII(), 0.7, 0.78),
                        new ValueInRange(parametersData.getIII(), 0.5, 0.6),
                        new ValueInRange(parametersData.getV(), 0.3, 0.4),
                        new ValueInRange(parametersData.getIV(), 0.58, 0.64),
                        new ValueInRange(parametersData.getT_60(), 65, 70),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.26),
                        new ValueInRange(parametersData.getS_15_30(), 0.16, 0.2),
                        new ValueInRange(parametersData.getVI_L(), 0.55, 0.60),
                        new ValueInRange(parametersData.getVII_L(), 0.65, 0.75),
                        new ValueInRange(parametersData.getII_30(), 0.35, 0.4),
                        new ValueInRange(parametersData.getI_30(), 0.28, 0.34)
                ),
                new Substance("Розы белые",
                        new ValueInRange(parametersData.getII(), 0.7, 0.78),
                        new ValueInRange(parametersData.getIII(), 0.5, 0.6),
                        new ValueInRange(parametersData.getV(), 0.3, 0.4),
                        new ValueInRange(parametersData.getIV(), 0.65, 0.69),
                        new ValueInRange(parametersData.getT_60(), 60, 70),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.26),
                        new ValueInRange(parametersData.getS_15_30(), 0.18, 0.24),
                        new ValueInRange(parametersData.getVI_L(), 0.55, 0.60),
                        new ValueInRange(parametersData.getVII_L(), 0.65, 0.75),
                        new ValueInRange(parametersData.getII_30(), 0.4, 0.5),
                        new ValueInRange(parametersData.getI_30(), 0.38, 0.44)
                ),
                new Substance("Яблоко красное на ветке",
                        new ValueInRange(parametersData.getII(), 0.63, 0.76),
                        new ValueInRange(parametersData.getIII(), 0.46, 0.59),
                        new ValueInRange(parametersData.getV(), 0.27, 0.37),
                        new ValueInRange(parametersData.getIV(), 0.57, 0.63),
                        new ValueInRange(parametersData.getT_60(), 54, 68),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.26),
                        new ValueInRange(parametersData.getS_15_30(), 0.19, 0.24),
                        new ValueInRange(parametersData.getVI_L(), 0.46, 0.57),
                        new ValueInRange(parametersData.getVII_L(), 0.36, 0.47),
                        new ValueInRange(parametersData.getII_30(), 0.34, 0.45),
                        new ValueInRange(parametersData.getI_30(), 0.36, 0.47)
                ),
                new Substance("Яблоко на земле",
                        new ValueInRange(parametersData.getII(), 0.6, 0.68),
                        new ValueInRange(parametersData.getIII(), 0.39, 0.49),
                        new ValueInRange(parametersData.getV(), 0.18, 0.3),
                        new ValueInRange(parametersData.getIV(), 0.47, 0.6),
                        new ValueInRange(parametersData.getT_60(), 50, 60),
                        new ValueInRange(parametersData.getS_30_60(), 0.16, 0.28),
                        new ValueInRange(parametersData.getS_15_30(), 0.1, 0.21),
                        new ValueInRange(parametersData.getVI_L(), 0.39, 0.57),
                        new ValueInRange(parametersData.getVII_L(), 0.36, 0.47),
                        new ValueInRange(parametersData.getII_30(), 0.2, 0.42),
                        new ValueInRange(parametersData.getI_30(), 0.07, 0.39)
                ),
                new Substance("Яблоко увядающее",
                        new ValueInRange(parametersData.getII(), 0.46, 0.5),
                        new ValueInRange(parametersData.getIII(), 0.3, 0.35),
                        new ValueInRange(parametersData.getV(), 0.22, 0.26),
                        new ValueInRange(parametersData.getIV(), 0.7, 0.79),
                        new ValueInRange(parametersData.getT_60(), 36, 40),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.26),
                        new ValueInRange(parametersData.getS_15_30(), 0.28, 0.30),
                        new ValueInRange(parametersData.getVI_L(), 0.38, 0.48),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.7),
                        new ValueInRange(parametersData.getII_30(), 0.7, 0.8),
                        new ValueInRange(parametersData.getI_30(), 0.4, 0.47)
                ),
                new Substance("Глина, известняк",
                        new ValueInRange(parametersData.getII(), 0.78, 0.83),
                        new ValueInRange(parametersData.getIII(), 0.63, 0.67),
                        new ValueInRange(parametersData.getV(), 0.42, 0.46),
                        new ValueInRange(parametersData.getIV(), 0.65, 0.7),
                        new ValueInRange(parametersData.getT_60(), 74, 76),
                        new ValueInRange(parametersData.getS_30_60(), 0.26, 0.29),
                        new ValueInRange(parametersData.getS_15_30(), 0.22, 0.26),
                        new ValueInRange(parametersData.getVI_L(), 0.62, 0.66),
                        new ValueInRange(parametersData.getVII_L(), 0.6, 0.7),
                        new ValueInRange(parametersData.getII_30(), 0.44, 0.51),
                        new ValueInRange(parametersData.getI_30(), 0.41, 0.5)
                ),
                new Substance("Снег чистый",
                        new ValueInRange(parametersData.getII(), 0.69, 0.77),
                        new ValueInRange(parametersData.getIII(), 0.52, 0.63),
                        new ValueInRange(parametersData.getV(), 0.36, 0.45),
                        new ValueInRange(parametersData.getIV(), 0.7, 0.72),
                        new ValueInRange(parametersData.getT_60(), 62, 74),
                        new ValueInRange(parametersData.getS_30_60(), 0.26, 0.29),
                        new ValueInRange(parametersData.getS_15_30(), 0.24, 0.25),
                        new ValueInRange(parametersData.getVI_L(), 0.56, 0.65),
                        new ValueInRange(parametersData.getVII_L(), 0, Integer.MAX_VALUE),
                        new ValueInRange(parametersData.getII_30(), 0.48, 0.53),
                        new ValueInRange(parametersData.getI_30(), 0.44, 0.48)
                )
        );
    }

    public static List<Substance> getBioassays(SubstancesParametersData parametersData) {
        return Arrays.asList(
                new Substance("Кал ребенка 0-6 м. норма",
                        new ValueInRange(parametersData.getII(), 0.58, 0.65),
                        new ValueInRange(parametersData.getIII(), 0.42, 0.49),
                        new ValueInRange(parametersData.getV(), 0.24, 0.31),
                        new ValueInRange(parametersData.getIV(), 0.57, 0.64),
                        new ValueInRange(parametersData.getT_60(), 50, 58),
                        new ValueInRange(parametersData.getS_30_60(), 0.2, 0.23),
                        new ValueInRange(parametersData.getS_15_30(), 0.16, 0.21),
                        new ValueInRange(parametersData.getVI_L(), 0.46, 0.54),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.73),
                        new ValueInRange(parametersData.getII_30(), 0.33, 0.44),
                        new ValueInRange(parametersData.getI_30(), 0.28, 0.39)
                ),
                new Substance("Кал ребенка 6-9 м. норма пр.",
                        new ValueInRange(parametersData.getII(), 0.66, 0.72),
                        new ValueInRange(parametersData.getIII(), 0.47, 0.55),
                        new ValueInRange(parametersData.getV(), 0.26, 0.36),
                        new ValueInRange(parametersData.getIV(), 0.57, 0.66),
                        new ValueInRange(parametersData.getT_60(), 56, 66),
                        new ValueInRange(parametersData.getS_30_60(), 0.21, 0.25),
                        new ValueInRange(parametersData.getS_15_30(), 0.16, 0.23),
                        new ValueInRange(parametersData.getVI_L(), 0.47, 0.57),
                        new ValueInRange(parametersData.getVII_L(), 0.63, 0.73),
                        new ValueInRange(parametersData.getII_30(), 0.35, 0.49),
                        new ValueInRange(parametersData.getI_30(), 0.27, 0.45)
                ),
                new Substance("Кал ребенка начальная стадия дисбиоза",
                        new ValueInRange(parametersData.getII(), 0.7, 0.86),
                        new ValueInRange(parametersData.getIII(), 0.55, 0.69),
                        new ValueInRange(parametersData.getV(), 0.39, 0.42),
                        new ValueInRange(parametersData.getIV(), 0.56, 0.72),
                        new ValueInRange(parametersData.getT_60(), 68, 74),
                        new ValueInRange(parametersData.getS_30_60(), 0.23, 0.27),
                        new ValueInRange(parametersData.getS_15_30(), 0.13, 0.26),
                        new ValueInRange(parametersData.getVI_L(), 0.56, 0.62),
                        new ValueInRange(parametersData.getVII_L(), 0.51, 0.75),
                        new ValueInRange(parametersData.getII_30(), 0.24, 0.5),
                        new ValueInRange(parametersData.getI_30(), 0.12, 0.45)
                ),
                new Substance("Кал ребенка  дисбиоз",
                        new ValueInRange(parametersData.getII(), 0.72, 1.1),
                        new ValueInRange(parametersData.getIII(), 0.57, 0.96),
                        new ValueInRange(parametersData.getV(), 0.42, 0.65),
                        new ValueInRange(parametersData.getIV(), 0.68, 0.87),
                        new ValueInRange(parametersData.getT_60(), 70, 90),
                        new ValueInRange(parametersData.getS_30_60(), 0.27, 0.3),
                        new ValueInRange(parametersData.getS_15_30(), 0.23, 0.26),
                        new ValueInRange(parametersData.getVI_L(), 0.62, 0.75),
                        new ValueInRange(parametersData.getVII_L(), 0.74, 0.8),
                        new ValueInRange(parametersData.getII_30(), 0.49, 0.63),
                        new ValueInRange(parametersData.getI_30(), 0.38, 0.5)
                )
        );
    }
}
